Prevent crash on Android 4.1.x - 4.3.x caused by jackson-databind.
+ Error: "NoClassDefFoundError: java.util.Objects".
+ Revert version update done in: db1173da74c2b7c1e296a612af88faf9bb281dc4.
+ Related: https://github.com/FasterXML/jackson-databind/issues/2599.

Resolves #50.