Fix instrumentation tests which launch an Activity.
+ Broken since AndroidX migration: 0fdc1af5606cccfeee4b3597a8dcff5f084ec067.
+ Error: "java.lang.RuntimeException: Could not launch activity ...
  android.util.AndroidRuntimeException: Calling startActivity()
  from outside of an Activity  context requires the
  FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?"
+ Successfully tested with:
  - LG Nexus 5 (Android 6.0.1, API 23)
  - HTC Nexus 9 (Android 7.1.1, API 25)
  - Google Pixel 2 (Android 10, API 29)

Co-authored-by: cketti <cketti@gmail.com>